(function() {var implementors = {};
implementors["arrayvec"] = [{"text":"impl&lt;A:&nbsp;Copy&gt; Copy for ArrayString&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A: Array&lt;Item = u8&gt; + Copy,<br>&nbsp;&nbsp;&nbsp;&nbsp;A::Index: Copy,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Copy&gt; Copy for CapacityError&lt;T&gt;","synthetic":false,"types":[]}];
implementors["base64"] = [{"text":"impl Copy for CharacterSet","synthetic":false,"types":[]},{"text":"impl Copy for Config","synthetic":false,"types":[]}];
implementors["encoding"] = [{"text":"impl Copy for DecoderTrap","synthetic":false,"types":[]},{"text":"impl Copy for EncoderTrap","synthetic":false,"types":[]},{"text":"impl Copy for ErrorEncoding","synthetic":false,"types":[]},{"text":"impl Copy for ErrorEncoder","synthetic":false,"types":[]},{"text":"impl Copy for ErrorDecoder","synthetic":false,"types":[]},{"text":"impl Copy for ASCIIEncoding","synthetic":false,"types":[]},{"text":"impl Copy for ASCIIEncoder","synthetic":false,"types":[]},{"text":"impl Copy for ASCIIDecoder","synthetic":false,"types":[]},{"text":"impl Copy for SingleByteEncoding","synthetic":false,"types":[]},{"text":"impl Copy for SingleByteEncoder","synthetic":false,"types":[]},{"text":"impl Copy for SingleByteDecoder","synthetic":false,"types":[]},{"text":"impl Copy for UTF8Encoding","synthetic":false,"types":[]},{"text":"impl Copy for UTF8Encoder","synthetic":false,"types":[]},{"text":"impl Copy for UTF8Decoder","synthetic":false,"types":[]},{"text":"impl Copy for Little","synthetic":false,"types":[]},{"text":"impl Copy for Big","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Copy&gt; Copy for UTF16Encoding&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Copy&gt; Copy for UTF16Encoder&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl Copy for Windows949Encoding","synthetic":false,"types":[]},{"text":"impl Copy for Windows949Encoder","synthetic":false,"types":[]},{"text":"impl Copy for EUCJPEncoding","synthetic":false,"types":[]},{"text":"impl Copy for EUCJPEncoder","synthetic":false,"types":[]},{"text":"impl Copy for Windows31JEncoding","synthetic":false,"types":[]},{"text":"impl Copy for Windows31JEncoder","synthetic":false,"types":[]},{"text":"impl Copy for ISO2022JPEncoding","synthetic":false,"types":[]},{"text":"impl Copy for ISO2022JPEncoder","synthetic":false,"types":[]},{"text":"impl Copy for GBK","synthetic":false,"types":[]},{"text":"impl Copy for GB18030","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Copy&gt; Copy for GBEncoding&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Copy&gt; Copy for GBEncoder&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl Copy for HZEncoding","synthetic":false,"types":[]},{"text":"impl Copy for HZEncoder","synthetic":false,"types":[]},{"text":"impl Copy for BigFive2003Encoding","synthetic":false,"types":[]},{"text":"impl Copy for BigFive2003Encoder","synthetic":false,"types":[]},{"text":"impl Copy for EncoderOnlyUTF8Encoding","synthetic":false,"types":[]}];
implementors["idna"] = [{"text":"impl Copy for Config","synthetic":false,"types":[]}];
implementors["lexical_core"] = [{"text":"impl Copy for ErrorCode","synthetic":false,"types":[]},{"text":"impl Copy for Error","synthetic":false,"types":[]}];
implementors["ryu"] = [{"text":"impl Copy for Buffer","synthetic":false,"types":[]}];
implementors["tinyvec"] = [{"text":"impl&lt;A:&nbsp;Copy + Array&gt; Copy for ArrayVec&lt;A&gt;","synthetic":false,"types":[]}];
implementors["unicode_bidi"] = [{"text":"impl Copy for Level","synthetic":false,"types":[]},{"text":"impl Copy for BidiClass","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()